<a href="https://colab.research.google.com/github/mari-zabel/coleta_analise_dados/blob/main/notebooks/Maria_Izabel_an%C3%A1lise_de_dados_Franca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução

## Importações de programas e bibliotecas

- O código abaixa indica os programas e bibliotecas que serão utilizados nesse arquivo

In [ ]:
import json #Interação com o formato do banco de dados
import os #Interação com o sistema operacional
import numpy as np #Analise de dados
import pandas as pd #Analise de dados
from google.colab import drive #google drive interação
drive.mount('/content/gdrive', force_remount=True) #acesso

Mounted at /content/gdrive

## Interação com o Google Drive

In [ ]:
caminho_padrao = "/content/gdrive/MyDrive" # comum a todos os usuários
caminho_especifico_dados = "/Opps/Notebooks/Dados/Franca/dom_franca_2024.json" # caminho especifico de cada usuário
caminho_completo = caminho_padrao + caminho_especifico_dados
caminho_completo

'/content/gdrive/MyDrive/Opps/Notebooks/Dados/Franca/dom_franca_2024.json'

# Análise exploratória inicial

## Acessando as informações dos arquivos

In [ ]:
dataset = pd.read_json(caminho_completo, orient="columns") #pd=pandas analise de dados do json
df_diarios = pd.json_normalize(dataset["_default"]) #transforma jason em tabela
df_diarios

,tipo_dado,plataforma,origem,origem_lower,nivel,cod_identificacao,categoria,data,num_ed,nome_arquivo,...,conteudo,coleta_pdf,dir_bd,codigo_bd,dir_base,nome_arq_bd,dir_arquivo,dir_local,arq_local_pdf,nome_bd_json
0,[Público],https://www.imprensaoficialmunicipal.com.br/,[Franca],[franca],[Municipal],3516200,[ordinario],[04/01/2024],[2433],[dom_franca_2024-01-04_ed-2433_ordinario],...,[NA],true,[/json],bd/001/002/3516200,[/media/hdvm04],[dom_franca_2024.json],[],NaN,NaN,NaN
1,[Público],https://www.imprensaoficialmunicipal.com.br/,[Franca],[franca],[Municipal],3516200,[ordinario],[05/01/2024],[2434],[dom_franca_2024-01-05_ed-2434_ordinario],...,[NA],true,[/json],bd/001/002/3516200,[/media/hdvm04],[dom_franca_2024.json],[],NaN,NaN,NaN
2,[Público],https://www.imprensaoficialmunicipal.com.br/,[Franca],[franca],[Municipal],3516200,[ordinario],[06/01/2024],[2435],[dom_franca_2024-01-06_ed-2435_ordinario],...,[NA],true,[/json],bd/001/002/3516200,[/media/hdvm04],[dom_franca_2024.json],[],NaN,NaN,NaN
3,[Público],https://www.imprensaoficialmunicipal.com.br/,[Franca],[franca],[Municipal],3516200,[ordinario],[09/01/2024],[2436],[dom_franca_2024-01-09_ed-2436_ordinario],...,[NA],true,[/json],bd/001/002/3516200,[/media/hdvm04],[dom_franca_2024.json],[],NaN,NaN,NaN
4,[Público],https://www.imprensaoficialmunicipal.com.br/,[Franca],[franca],[Municipal],3516200,[ordinario],[10/01/2024],[2437],[dom_franca_2024-01-10_ed-2437_ordinario],...,[NA],true,[/json],bd/001/002/3516200,[/media/hdvm04],[dom_franca_2024.json],[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Público,https://www.imprensaoficialmunicipal.com.br/,Franca,franca,Municipal,3516200,ordinario,24/12/2024,2674,dom_franca_2024-12-24_ed-2674_ordinario,...,NA,true,/media/hdvm04/bd/001/002/3516200/json/dom_fran...,bd/001/002/3516200,NaN,NaN,NaN,/media/hdvm04/bd/001/002/3516200,/media/hdvm04/bd/001/002/3516200/pdf/2020_2029...,dom_franca_2024
439,Público,https://www.imprensaoficialmunicipal.com.br/,Franca,franca,Municipal,3516200,ordinario,25/12/2024,2675,dom_franca_2024-12-25_ed-2675_ordinario,...,NA,true,/media/hdvm04/bd/001/002/3516200/json/dom_fran...,bd/001/002/3516200,NaN,NaN,NaN,/media/hdvm04/bd/001/002/3516200,/media/hdvm04/bd/001/002/3516200/pdf/2020_2029...,dom_franca_2024
440,Público,https://www.imprensaoficialmunicipal.com.br/,Franca,franca,Municipal,3516200,ordinario,27/12/2024,2676,dom_franca_2024-12-27_ed-2676_ordinario,...,NA,true,/media/hdvm04/bd/001/002/3516200/json/dom_fran...,bd/001/002/3516200,NaN,NaN,NaN,/media/hdvm04/bd/001/002/3516200,/media/hdvm04/bd/001/002/3516200/pdf/2020_2029...,dom_franca_2024
441,Público,https://www.imprensaoficialmunicipal.com.br/,Franca,franca,Municipal,3516200,ordinario,28/12/2024,2677,dom_franca_2024-12-28_ed-2677_ordinario,...,NA,true,/media/hdvm04/bd/001/002/3516200/json/dom_fran...,bd/001/002/3516200,NaN,NaN,NaN,/media/hdvm04/bd/001/002/3516200,/media/hdvm04/bd/001/002/3516200/pdf/2020_2029...,dom_franca_2024
442,Público,https://www.imprensaoficialmunicipal.com.br/,Franca,franca,Municipal,3516200,ordinario,31/12/2024,2678,dom_franca_2024-12-31_ed-2678_ordinario,...,NA,true,/media/hdvm04/bd/001/002/3516200/json/dom_fran...,bd/001/002/3516200,NaN,NaN,NaN,/media/hdvm04/bd/001/002/3516200,/media/hdvm04/bd/001/002/3516200/pdf/2020_2029...,dom_franca_2024

## Pré-análise

In [ ]:
df_diarios.shape

(443, 22)

In [ ]:
df_diarios.columns

Index(['tipo_dado', 'plataforma', 'origem', 'origem_lower', 'nivel',
       'cod_identificacao', 'categoria', 'data', 'num_ed', 'nome_arquivo',
       'tamanho', 'link_pdf', 'conteudo', 'coleta_pdf', 'dir_bd', 'codigo_bd',
       'dir_base', 'nome_arq_bd', 'dir_arquivo', 'dir_local', 'arq_local_pdf',
       'nome_bd_json'],
      dtype='object')

In [ ]:
df=df_diarios[["data","origem","categoria","num_ed","nome_arquivo","plataforma","nivel"]]
df

,data,origem,categoria,num_ed,nome_arquivo,plataforma,nivel
0,[04/01/2024],[Franca],[ordinario],[2433],[dom_franca_2024-01-04_ed-2433_ordinario],https://www.imprensaoficialmunicipal.com.br/,[Municipal]
1,[05/01/2024],[Franca],[ordinario],[2434],[dom_franca_2024-01-05_ed-2434_ordinario],https://www.imprensaoficialmunicipal.com.br/,[Municipal]
2,[06/01/2024],[Franca],[ordinario],[2435],[dom_franca_2024-01-06_ed-2435_ordinario],https://www.imprensaoficialmunicipal.com.br/,[Municipal]
3,[09/01/2024],[Franca],[ordinario],[2436],[dom_franca_2024-01-09_ed-2436_ordinario],https://www.imprensaoficialmunicipal.com.br/,[Municipal]
4,[10/01/2024],[Franca],[ordinario],[2437],[dom_franca_2024-01-10_ed-2437_ordinario],https://www.imprensaoficialmunicipal.com.br/,[Municipal]
...,...,...,...,...,...,...,...
438,24/12/2024,Franca,ordinario,2674,dom_franca_2024-12-24_ed-2674_ordinario,https://www.imprensaoficialmunicipal.com.br/,Municipal
439,25/12/2024,Franca,ordinario,2675,dom_franca_2024-12-25_ed-2675_ordinario,https://www.imprensaoficialmunicipal.com.br/,Municipal
440,27/12/2024,Franca,ordinario,2676,dom_franca_2024-12-27_ed-2676_ordinario,https://www.imprensaoficialmunicipal.com.br/,Municipal
441,28/12/2024,Franca,ordinario,2677,dom_franca_2024-12-28_ed-2677_ordinario,https://www.imprensaoficialmunicipal.com.br/,Municipal
442,31/12/2024,Franca,ordinario,2678,dom_franca_2024-12-31_ed-2678_ordinario,https://www.imprensaoficialmunicipal.com.br/,Municipal

In [ ]:
df['data'] = df['data'].apply(lambda x: str(x[0]) if isinstance(x, list) and len(x) > 0 else x)
datas=df["data"].value_counts()
datas

<ipython-input-26-c4bff69d73fd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['data'] = df['data'].apply(lambda x: str(x[0]) if isinstance(x, list) and len(x) > 0 else x)

data
04/01/2024    2
05/01/2024    2
06/01/2024    2
09/01/2024    2
10/01/2024    2
             ..
24/12/2024    1
25/12/2024    1
27/12/2024    1
28/12/2024    1
31/12/2024    1
Name: count, Length: 246, dtype: int64